import type { Metadata } from "next";
import { Inter, Itim } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const itim = Itim({ weight: "400", style: "normal", subsets: ["latin"]}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={itim.className}><div className="navChildren">{children}</div></body>
    </html>
  );
}
